Fake_app/Fake_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mbam/', include('mbam.urls')),
    path('jquery/', include('jquery.urls')),
    path('youtube/', include('youtube.urls')),
    path('exam/', include('exam.urls')),
]

Fake_app/exam/urls.py
from django.urls import path
from . import views as ex_views

app_name = 'exam'
urlpatterns = [
    path('', ex_views.index, name="main"),
    path('push', ex_views.push, name="push"),
]

Fake_app/jquery/urls.py
from django.urls import path
from . import views as jq_views

app_name = 'jq'
urlpatterns = [
    path('', jq_views.index, name="index"),
    path('find/', jq_views.find, name="find"),
]

Fake_app/jquery/views.py
from django.shortcuts import render, redirect
import requests
from bs4 import BeautifulSoup
from django.http.response import HttpResponse
# selenium
from selenium import webdriver
from time import sleep
import random
# Create your views here.

def index(request):
    return render(request, 'jquery/index.html')


def find(request):
    # 전역으로 넣으면 바로 실행되서 함수안에..
        
    id = request.POST['id']
    pwd = request.POST['pwd']
    types = request.POST['types']
    region = request.POST['region']
    
    message ="성공했습니다"
    context = {
        'message' : message,
    }
    # 로그인 함수
    Login(id, pwd, region, types)
    
    return HttpResponse('', status=204 )    
    #return render(request, 'jquery/index.html')

# 셀레니움으로 로그인 하는 부분
def Login(id, pwd, region, types):
    driver = webdriver.Chrome('C:\Crawling\Selenium\chromedriver.exe')
    driver.get('http://mbam4.com/')
    driver.find_element_by_name('mb_id').send_keys(id)
    sleep(0.3)
    driver.find_element_by_name('mb_password').send_keys(pwd)
    driver.find_element_by_xpath('//*[@id="miso_sidelogin"]/div/div[1]/button').click()

    # 변수를 str로 받는다
    # value를 바꿨는데 1 로 나오는 이유는 아직 모르겠음. 
    
    address1 = '//*[@id="MB-main-header"]/aside[1]/section/ul/li['+types+']/a'
    address2 = '//*[@id="MB-main-header"]/aside[1]/section/ul/li['+types+']/ul/li['+region+']/div/div[2]'
    driver.find_element_by_xpath(address1).click()
    sleep(0.5)  
    driver.find_element_by_xpath(address2).click()
    sleep(0.5)

    # 페이지를 자동으로 넘기기 반복문으로  
    for j in range (4,7,1):
        count = str(j)
        page = '//*[@id="fboardlist"]/div[3]/ul/li['+count+']/a'
        
        driver.find_element_by_xpath(page).click()                                   
        sleep(0.5)

        for i in range(2,22,1):
            s = str(i) 
            address = '//*[@id="list-body"]/li['+s+']/div[2]/a/div/div[2]/span'
            driver.find_element_by_xpath(address).click()
            sleep(0.5)
            # html 에 필요한 값들만 파싱하기 bs4로 사용해서
            req = driver.page_source
            soup = BeautifulSoup(req, 'html.parser')
            # 같은 닉넴이 있을때는 댓글을 달지 않게 만들기
            #shop = soup.select_one('.table > tbody > tr > td')
            #manager = soup.select_one('.table > tbody > .bg0 > td')
            # 리스트 형태
            data = soup.select('.table > tbody > tr > td')
            shop = data[0].text
            manager = data[1].text
            message = [
                shop+'의 '+manager +'언니와 즐달하신 후기 잘보고 가염',
                shop+'의 '+manager +'언니 저도 보고 싶네영~!',
                manager +'언니 죽여주네염~~~~~!',
                manager +'언니랑 즐달했네여~!',
                '후기보니 저두 ' + manager + '언니랑 놀구 싶네영~!',
                '당장 ' + shop +'에 예약해 ' + manager + '언니 봐야겠네영',
                manager +'언니가 죽입니당. 한 번 달려야겠네영ㅋㅋㅋ',
                '보장된 ' + shop +'이군요. ' + manager +'언니 후기 잘봤어영~!',
                '저두 달리고 싶네영 ㅠㅠ ' + manager + '언냐 좋네영ㅋㅋㅋㅋ',
                '즐달하신 후기 잘 보고 갑니당~! ' + manager + '언냐 기억해둘께영 ㅋㅋㅋㅋ',
                shop +'의 ' + manager + '언냐 좋네염 ㅋㅋㅋㅋㅋ',
                '후기보니 넘나 달리고 싶어집니당 '+manager+'언냐 후기 잘봤어염',
                '부럽습니당 '+manager+'언냐 후기 잘봤어염',
                manager + '언냐 후기 잘봤어염',
            ]    
            # 도토리개수
            dotori = soup.select('.paddingssang')
            dotori = dotori[3].text

            finds= soup.select('.media-body > .media-heading > b > a > span.member')
            #finds_all  = soup.select('.media-body > .media-heading > b > a > span.member')
            # keep 이라는 배열은 선언후 크롤링한 결과값을 저장
            nick = ' 오징어대마왕'
            #print(finds.text)
            keep = []
            for j in range(len(finds)):      
                keep.append(finds[j].text)    
        
            if( nick in keep):
                # 있을땐 수정 후에 댓글 : id 값이 계속 변경되서 불가
                driver.find_element_by_name('wr_content').send_keys('여기는 그냥 지나칠꺼야')
                sleep(3)
                pass 
            else:
                driver.find_element_by_name('wr_content').send_keys(random.choice(message))
                sleep(3)
                driver.find_element_by_xpath('//*[@id="btn_submit"]').click()
                end = '끝냈습니다.' 
            

Fake_app/jquery/templates/jquery/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--CSS 꾸미기-->
    {% block style %}
    
    {% endblock %}
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>


<body>
    {% block content %}
    
    {% endblock %}        
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    {% block script %}

    {% endblock %}
</body>


</html>

Fake_app/jquery/templates/jquery/index.html
{% extends 'jquery/base.html' %}
{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="center" class="container">
  <h4>메크로 프로그램</h4>
  <span>키, 립, 핸플은 지역2번부터</span>
  <form method="POST" class="form-inline" action="{% url 'jq:find' %}">
    <input type="hidden" name="csrfmiddlewaretoken" value={{csrf_token}}>
    <input type="text" name="id" placeholder="아이디 입력">
    <input type="text" name="pwd" placeholder="비밀번호 입력"><br><br>

    <select class="types" name="types" id="types">
      <option selected>종목</option>
      <option value="2">오피</option>
      <option value="3">건마</option>
      <option value="4">휴게</option>
      <option value="5">안마</option>
      <option value="6">술집</option>
      <option value="7">키방</option>
      <option value="8">립</option>
      <option value="9">핸플</option>
    </select>

    <select class="region" id="region" name="region">
      <option selected>지역</option>
      <option value="1">서울</option>
      <option value="2">경기</option>
      <option value="3">인부천</option>
    </select>

    <button type="submit" class="btn btn-primary my-1" onclick="">Submit</button>
  </form>
</div>
{% endblock %}

{% block script %}
<script>
function test(){
  var re = document.getElementById('region')

  alert(re)  

  
}
</script>
{% endblock %}

<!--
<div class="container">
  <button type="button" class="btn btn-secondary" id="seoul">서울</button>
  <button type="button" class="btn btn-secondary" id="biseoul">비강남</button>
</div>-->

Fake_app/jquery/templates/jquery/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .bg-red{
            background-color: red;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <h1 id="title">JS 수업</h1>
    <h2 id="joke">JS 재미없음</h2>
    <!-- <p>오늘은 금요일</p> -->
    <!-- <div class="p-list"> -->
        <p class="element">요소 1</p>
        <div class="blue">요소 2</div>
        <div class="blue">요소 3</div>
        <p><span class="four">요소 4</span></p>
        <!-- 
            > document.querySelectorAll('.p-list span');
            p-list안에있는 span
            < NodeList [span.four]
            
            > document.querySelectorAll('.p-list, span');
            < NodeList(2) [div.p-list, span.four]
            > document.querySelectorAll('.p-list > .element');
            < NodeList(3) [p.element, p.element, p.element]
         -->
        <p class="bg-red">요소 5</p>

        <form class="mb-5 mt-5">
            글쓰기
            <input type="text" class="form-control" id="articleForm">
            <button type="button" class="btn btn-primary">글쓰기</button>
            <div class="pb-5"></div>
            댓글쓰기
            <input type="text" class="form-control" id="commentForm">
            <button type="button" class="btn btn-primary" id="submitComment">댓글쓰기</button>
        </form>

        <div class="commentList">
            <ul class="list-group">
                <li class="list-group-item">
                    첫번째 댓글<button type="button" class="btn btn-warning">수정</button>
                </li>
                <li class="list-group-item">
                    두번째 댓글<button type="button" class="btn btn-warning">수정</button>
                </li>
                <li class="list-group-item">
                    세번째 댓글<button type="button" class="btn btn-warning">수정</button>
                </li>
                <li class="list-group-item">
                    세번째 댓글<button type="button" class="btn btn-warning">수정</button>
                </li>    
            </ul>
        </div>


    <!-- </div> -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        console.dir($);
        // click에 대한 listener
        var btn = document.getElementById('submitComment');
        // click하면 function 동작
        btn.addEventListener('click', function(){
            // commentForm에 있는 내용을 받아서
            var commentForm = document.getElementById('commentForm');
            if(commentForm.value == ''){
                alert('빈칸은 입력할 수 없습니다.');
                return;
            }

            // alert 혹은 console에 출력
            // console.dir(commentForm);
            console.log(commentForm.value);

            
            // 댓글을 추가할 위치를 찾아서 -> ul class="list-group"
            var position = document.querySelector('.list-group');
            console.dir(position);
            // 추가 할 HTML 태그 모양을 잡고
            var appendingTag = document.createElement('li.list-group-item');
            var appendingSpan = document.createElement('span');

            appendingTag.classList.add('list-group-item');
            appendingSpan.classList.add('float-right');          

            appendingTag.innerText = commentForm.value;
            appendingSpan.innerHTML = '<button type="button" class="btn btn-warning">수정</button>';
            appendingTag.appendChild(appendingSpan);
            commentForm.value = '';

            
            
            console.dir(appendingTag);
            // `<li class="list-group-item">
            //     JS로 추가된 댓글
            //     <span class="float-right">
            //         <button type="button" class="btn btn-warning">수정</button>
            //     </span>
            // </li>`
            
            
            // 해당 위치에 추가
            position.prepend(appendingTag);
            // appendChild vs prepend


        })



        // console.log("Hello World!")
        
        // 요소 찾아서 이벤트를 주고
        var joke = document.getElementById('joke');
        // 어떤 동작을 할지
        // joke.onclick = function(){
        //     alert("fake");
        // }

        // event, 발생할 내용
        // joke.addEventListener('click', function(){

        // 요소.이벤트리스너달기('이벤트명', function(){ 
        //function -> event handler })

        //     alert('FAKE');
        // })


        // pTag 다 불러오기
        var pList = document.getElementsByTagName('p');
        // console.log(pList);
        // HTMLCollection(5) [p.element, p.element, p.element, p, p]

        // for(var i=0; i<pList.length; i++){
        //     pList[i].addEventListener('click', function(){
        //     alert("pTag Event");
        //     })
        // }
        
        // pList.forEach(function(element){
        //     element.addEventListener('click', function(){
        //         alert('이건 안됨');
        //     })
        // })

        // var pList2 = document.querySelectorAll('p');
        var pList2 = document.querySelectorAll('.blue');
        // console.log(pList2);
        // NodeList(5) [p.element, p.element, p.element, p, p]
        
        pList2.forEach(function(element){
            element.addEventListener('click', function(){
                // alert('이건 됨');

                // 속성setAttribute('속성 명', '속성 값')
                // element.setAttribute('class', 'p-tag')
                // class="element" -> class="p-tag"

                // if(confirm("이 태그를 삭제하시겠습니까?")){
                //     // element.classList.add('bg-red');
                //     // element.classList.remove('bg-red');
                //     element.classList.toggle('bg-red');

                //     // element.setAttribute('class', 'bg-red');
                //     // element.setAttribute('style', 'display: none;');
                //     // 새로고침하면 다시 보임
                // }

                // click -> blue
                // console.dir(element);
                // <p><span class="four">요소 4</span></p>
                // innerHTML: "<span class="four">요소 4</span>"
                // innerText: "요소 4"
                // if(confirm("이 태그를 내용을 출력하시겠습니까?")){
                //     // alert(element.innerText);
                //     // alert(element.innerHTML);
                //     element.classList.toggle('alert-primary')
                // }

            })
        })

        // 여러개를 선택할 때는 querySelectorAll 사용(getElement보다는)

    </script>
</body>
</html>