Crawling/Crawling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webcrawling/', include('webcrawling.urls')),
]

Crawling/webcrawling/urls.py
from django.urls import path
from . import views as views_web

app_name = 'webcrawling'

urlpatterns = [
    path('', views_web.index, name="index"),
    path('nfind/', views_web.nfind, name="nfind"),
    path('wfind/', views_web.wfind, name="wfind"),
    #path('articles/<int:article_id>/delete/', article_views.delete, name="delete"),
    #path('find/<int:data_id>/delete/', views_web.delete, name="delete"),
    path('delete_all/', views_web.delete_all, name="delete_all"),
    path('<int:data_id>/delete_one/', views_web.delete_one, name="delete_one"),
]

Crawling/webcrawling/models.py
from django.db import models

# Create your models here.

class data(models.Model):
    title = models.TextField()
    web = models.TextField()

Crawling/webcrawling/views.py
from django.shortcuts import render, redirect
import requests
from bs4 import BeautifulSoup
from .models import data
# Create your views here.

def index(request):
   
    return render(request, 'index.html')

def nfind(request):
    # 네이버 검색시 base가 되는 url 
    baseUrl ='https://search.naver.com/search.naver?where=post&sm=tab_jum&query='
    # index의 검색어 받아오기   
    search = request.GET['nname']
    url = baseUrl + search
    html = requests.get(url).text 
    # html을 긁어옴
    soup = BeautifulSoup(html, "html.parser")
    title = soup.find_all(class_="sh_blog_title")
    # print(title)
    # 값이 있을때
    if title:
        for i in title:
            datas = data()
            datas.title = i.attrs['title']
            datas.web = i.attrs['href']
            datas.save()
        alldata = data.objects.all()
        context = {
            'alldata' : alldata,
        }    
        return render(request, 'index.html', context)    
    else :
        return render(request, 'error.html')

def wfind(request):
    baseUrl = 'https://ko.wikipedia.org/wiki/'
    search = request.GET['wname']
    url = baseUrl + search
    html = requests.get(url).text 
    # html을 긁어옴
    soup = BeautifulSoup(html, "html.parser")
    print(soup)
    return render(request, 'index.html')


def delete_one(request, data_id):
    datas = data.objects.get(id=data_id)
    datas.delete()

    datas = data.objects.all()
    context = {
        'alldata' : datas,
    }    

    return render(request, 'index.html', context)


def delete_all(request):
    data_all = data.objects.all()
    data_all.delete()
    return render(request, 'index.html')

Crawling/webcrawling/templates/error.html
없을땐 에러 페이지 날리기

Crawling/webcrawling/templates/index.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>검색</title>
    <style>
        * {
            font-size: 16px;
            font-family: Consolas, sans-serif;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <form method="get" action="{% url 'webcrawling:nfind' %}">
            <input type="text" name="nname" placeholder="네이버 검색">
            <input type="submit" value="누르기">
            <input type="button" value="리셋버튼" onclick="location.href='{% url 'webcrawling:delete_all' %}'">
        </form>
        <!--<input type="button" value="리셋" a href="{% url 'webcrawling:delete_all' %}"></a>-->
    </div>

    <div class="container">
        <form method="get" action="{% url 'webcrawling:wfind' %}">
            <input type="text" name="wname" placeholder="나무위키 검색">
            <input type="submit" value="누르기">
            <input type="button" value="리셋버튼" onclick="location.href='{% url 'webcrawling:delete_all' %}'">
        </form>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">타이틀</th>
                    <th scope="col">웹주소</th>
                    <th scope="col"></th>

                </tr>
            </thead>
            <tbody>
                {% for data in alldata %}
                <tr>
                    <td>{{data.title}}</td>
                    <td>{{data.web}}</td>
                    <td><input type="button" name="data_id" value="지우기"
                            onclick="location.href='{% url 'webcrawling:delete_one' data.id %}'"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

Crawling/webcrawling/templates/reset.html
리셋 페이지. 

페이지 넘어가는거 확인